CONTRIBUTING.rst
- renamed `BrainSpace` to `BrainStat`
- fix link pointing to issues
=> small fix to CONTRIBUTING.rst

surfstat/python/SurfStatEdg.py, surfstat/python/matlab_functions.py, surfstat/tests/test_SurfStatEdg.py
This branch can be used to fix the following issues with SurfStatEdg
1. Incorrect output is provided for larger 'lat' matrices (see new test 4 for SurfStatEdg)
2. An error is thrown for 2D 'lat' matrices.
=> [FIX] Bug fixes for SurfStatEdg

surfstat/python/stat_threshold.py, surfstat/tests/test_statthreshold.py
statthreshold now handles every shape of p_val_peak and p_val_extent
=> [ENH] Fixed stat_threshold p_val_peak shape handling.

surfstat/python/matlab_functions.py, surfstat/tests/test_statthreshold.py
Hello hello!
a potential bug in `stat_threshold.py` is demonstrated with test_18 in `test_statthreshold.py` .
=> bug demonstared with test_18

surfstat/matlab/SurfStatAvSurf.m, surfstat/python/SurfStatAvSurf.py, surfstat/surfstat_wrap.py, surfstat/tests/test_SurfStatAvSurf.py
SurfStatAvSurf is born. Currently the tests are a bit lackluster because I'm not sure how to create a MATLAB function handle in Python. 
To do: 
- Add support for 2d arrays to Python. 
- Figure out how to pass function handles to MATLAB.
=> [ENH] Added SurfStatAvSurf.

requirements.txt
This PR adds a requirements file for the Python dependencies. I have not included pytest (since running the tests isn't really a requirement for the package) and brainspace (I'm assuming that the remaining dependencies will be removed in future PRs). I've set the package versions to be equal to or greater than the current version installed by pip on Python 3.7.
=> [DOC] Added a requirements.txt file.

.azure-pipelines.yml, .github/workflows/python_ci.yml, .github/workflows/python_coverage.yml, brainstat/stats/__init__.py, matlab/readme.md
This PR modifies both Github Actions and Azure to trigger only on changes in the Python/MATLAB code, respectively.  It also disables Github actions' fail-fast procedure whereby all jobs fail if one fails.
=> [GIT] CI triggers only on code changes.

.github/labeler.yml, .github/workflows/label.yml
Just a fun lil addition I made when I was procrastinating :P . 
This PR sets up automatic labeling of PRs. Label keys/values are in .github/labeler.yml.
=> [GIT] PR Labeler

docs/conf.py
Somehow sphinx seems to be parsing lines that are commented out in conf.py. This PR simply removes those lines entirely.
=> [FIX] Fixed conf.py parsing

setup.py
Version number update necessary to push the newest version to test-pypi
=> [Release] 0.0.1-alpha.3

brainstat/mesh/data.py
Small change to change numpy.array to numpy.ndarray.
=> [DOC] numpy.array -> numpy.ndarray

brainstat/mesh/data.py
Hi,
this mini PR is my first trial for the Sphinx. So far, the html looked good to me, when it was run locally. 
Let me know if the docs for **brainstat.mesh.data** (mesh_normalize, mesh_smooth, mesh_standardize) look good enough to be merged.
=> docs polished in brainstat/mesh/data.py

.github/workflows/python_unittests.yml, docs/generic/install.rst, requirements.txt, setup.cfg, setup.py
This PR fixes installation dependencies by updating the setup.py, requirements.txt and installation guide.
=> [FIX] Fixed installation dependencies

brainstat/tests/datagen_mesh_edges.py, brainstat/tests/test_mesh_edges.py
Hi,
this PR generates the test data for [test_mesh_edges.py](https://github.com/MICA-MNI/BrainStat/blob/master/brainstat/tests/test_mesh_edges.py).
=> Datagen mesh edges

.github/workflows/MATLAB_unittests.yml, .github/workflows/label.yml, .github/workflows/python_black.yml, .github/workflows/python_unittests.yml, brainstat/stats/SLM.py, brainstat/tests/datagen_linear_model.py, brainstat/tests/datagen_mesh_edges.py
See #139. A black refactor was also added to this PR as its failing on master.
=> [GIT] Update CI triggers.

brainstat/mesh/data.py, requirements.txt, setup.py
See #139. This PR simply fixed the lint check.
=> [REF] Replaces numpy_groupies with np.bincount

brainstat/context/meta_analysis.py, brainstat/context/utils.py, brainstat/mesh/interpolate.py, docs/python/tutorials/plot_tutorial_02_context.py
This PR modifies our NiMare usage to use a procedure identical to the old Neurosynth implementation. Furthermore it adds a tutorial 2 for context decoding.
=> [ENH, DOC] Context decoding tutorial 

brainstat/tests/datagen_peak_clus.py, brainstat/tests/test_peak_clus.py
Inspiration of this PR comes from PR #134.
Below is a summary of generated tests for `peak_clus` function.
Tests 1-4 test input variance of slm (a dict)
Tests 5-8 test input of slm (a dict), reselspvert and edg. 
Tests 8-12 test input of slm (a dict), reselspvert and edg.
Tests 13-16 test input variance of slm (BSPolydata).
Tests 17-20 test input variance of slm (BSPolydata), reselspvert.
Tests 21-24 test input variance of slm (BSPolydata), reslspvert and nonsense.
=> [TST] Datagen peak clus

brainstat/tests/datagen_resels.py, brainstat/tests/test_resels.py
Test data generation for brainstat//tests/test_resels.py .
=> [TST] Datagen resels

brainstat/tests/datagen_t_test.py, brainstat/tests/test_t_test.py
Test data generation for [test_t_test.py](https://github.com/MICA-MNI/BrainStat/blob/master/brainstat/tests/test_t_test.py)
=> Datagen ttest

brainstat/tests/datagen_mesh_normalize.py, brainstat/tests/test_mesh_normalize.py
Test data generation for [test_mesh_normalize](https://github.com/MICA-MNI/BrainStat/blob/master/brainstat/tests/test_mesh_normalize.py).
=> Datagen mesh normalize

brainstat/mesh/utils.py, brainstat/stats/terms.py, brainstat/tests/datagen_linear_model.py, brainstat/tests/test_linear_model.py, brainstat_matlab/context/histology/read_histology_profile.m, brainstat_matlab/stats/@SLM/SLM.m, brainstat_matlab/tests/@test_precomputed/test_precomputed.m
This PR adds the datagen and tests for mixed effects linmod. To that end it also fixes a bug in the Term class.
=> [TST] Add mixed effects to datagen and tests for linmod

brainstat/stats/SLM.py
Fixes an issue where an SLM without a mask would have an unbound variable.
=> [FIX] Fix unbound variable in SLM

brainstat/stats/SLM.py, brainstat_matlab/stats/@SLM/SLM.m
=> [FIX] Fixed a bug causing a two-tailed correction when a two-tailed test was run

.github/labeler.yml, .github/workflows/python_unittests.yml, .github/workflows/tagged_release.yml, CONTRIBUTING.rst, LICENSE, brainstat/__init__.py, brainstat/context/genetics.py, brainstat/context/meta_analysis.py, brainstat/context/utils.py, brainstat/datasets/base.py, brainstat/stats/SLM.py, brainstat/stats/_linear_model.py, brainstat/stats/_multiple_comparisons.py, brainstat/stats/_t_test.py, brainstat/stats/terms.py, brainstat/tests/test_datasets.py, brainstat/tests/test_fdr.py, brainstat/tests/test_linear_model.py, brainstat/tests/test_random_field_theory.py, brainstat/tests/test_t_test.py, brainstat_matlab/datasets/fetch_parcellation.m, brainstat_matlab/tests/@test_datasets/test_datasets.m, docs/generic/install.rst, mypy.ini, setup.cfg, setup.py
- Resolves #206 
- Resolves #200
- Resolves #204
=> Version 0.2.3

setup.py
=> [FIX] Include data_json and logging.conf with distribution

.github/workflows/MATLAB_unittests.yml, brainstat_matlab/+brainstat_utils/+validators/mustBeOfSize.m, brainstat_matlab/context/compute_histology_gradients.m, brainstat_matlab/context/compute_mpc.m, brainstat_matlab/context/surface_decoder.m, brainstat_matlab/datasets/fetch_parcellation.m, brainstat_matlab/datasets/fetch_template_surface.m, brainstat_matlab/io/read_volume.m, brainstat_matlab/stats/@SLM/SLM.m
=> [TST] Add R2019b to MATLAB testing

brainstat/context/meta_analysis.py, brainstat/context/resting.py, brainstat/datasets/base.py, brainstat/mesh/interpolate.py
- Fixes feature names containing spaces.
- Adds CIVET compatibility by nearest neighbour interpolation for parcellations and gradients.
=> [FIX] Fixes incomplete label names in the context decoder

brainstat/_utils.py, brainstat/context/genetics.py, brainstat/data/data_urls.json, brainstat/datasets/base.py, brainstat_matlab/data/data_urls.json
Updates the pre-computed genetics matrices for MATLAB to the newer abagen algorithm. Also fixes the Glasser parcellation on fsaverage.
=> [REF] Update genetics precomputation

brainstat/stats/terms.py
Fixes #292 
Propose a fix for issue #292 
I can add a non regression test if the fix is accepted.
=> [FIX] Fix `TypeError` in `remove_duplicate_columns`
